### PR TITLE
Updated package.json

### PR DESCRIPTION
**Pull request by sebbi08**
fixed version of xmldom to 0.1.22 because this is the last working version

### CODE REVIEW

**Comment by bdukes** [comment]
@sebbi08, were you having a particular issue with the task?  The tests were failing because of a formatting issue (i.e. the tests were too strict), but the behavior of the task should still be fine.  I've updated the dependencies and gotten the tests to pass, so I'll publish a new version, but let me know if you're having any other issues you need addressed.

Thanks!

**Comment by sebbi08** [comment]
i have the following configuration

```
addTheme: {
                options: {
                    namespaces: {
                        "l": "sap.ui.layout",
                        "f": "sap.ui.layout.form",
                        "core": "sap.ui.core"
                    },
                    valueType: "append",
                    xpath: "some xpath",
                    value: '<core:Item key="sov" text="Sovanta Theme"/>'
                },
                files: {
                    "dest.xml": some.xml
                }
            }
```

and it results in


`<core:Item key="sov" text="Sovanta Theme" xmlns:core=""/></Select>`

there shuld be no extra xmln:core="" and when using the version 0.1.22 there is none

**Comment by bdukes** [comment]
@sebbi08 this was probably a bug in xmldom that it was supporting that, because the way this task was adding the XML didn't support namespaces.  I've adjusted that code (see 9bf2f345d4d3d8be2f13eee6fa6796c79def55f4) and published as 0.9.0.  Let me know if you continue to run into an issue

**Comment by sebbi08** [comment]
hi,
sry for the late answer, the new version fixed my problem.

Thank you.
Sebbi

**Pull request closed without merging**
